sudo: false

env:
  global:
    - GO111MODULE=on

language: go

install:
  - "go get golang.org/x/lint/golint"
  - "make deps"

jobs:
  include:
    - go: "1.11.x"
    - go: "master"
    - language: elm
      elm: "0.19.0"
      install:
        - "cd ui"
        - "npm ci"
      script:
        - "elm-format --validate ."
        - "npm run build"
    - stage: deploy
      install: "true"
      script: "curl -sL https://git.io/goreleaser | bash"
      addons:
        apt:
          packages:
            - rpm

stages:
  - test
  - name: deploy
    if: tag IS present
