language: go
sudo: false

env:
  - DEPLOY_WITH_MAJOR="1.9"

before_script:
  - go get github.com/golang/lint/golint

go:
  - 1.9.x
  - "1.10"

deploy:
  provider: script
  script: etc/travis-deploy.sh
  on:
    tags: true
    branch: master
