language: go
sudo: false

addons:
  apt:
    packages:
      - rpm

env:
  - DEPLOY_WITH_MAJOR="1.10"

before_script:
  - go get github.com/golang/lint/golint
  - make deps

go:
  - "1.10.1"

deploy:
  provider: script
  script: etc/travis-deploy.sh
  on:
    tags: true
    branch: master
