language: go
sudo: false

before_script:
  - go vet ./...

go:
  - 1.8.5
  - 1.9.2

script: go test -race -v ./...

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
