language: go
sudo: false

addons:
  apt:
    packages:
      - rpm

env:
  global:
    - GO111MODULE=on

install:
  - go get golang.org/x/lint/golint
  - make deps

go:
  - "1.11.x"
  - "tip"

jobs:
  include:
    - stage: deploy
      script: etc/travis-deploy.sh
      go: "1.11.x"

stages:
  - test
  - name: deploy
    if: tag IS present
