sudo: false

env:
  global:
    - GO111MODULE=on

# deploy will use first go version listed below.
language: go
go:
  - "1.11.x"
  - "master"

install:
  - "go get golang.org/x/lint/golint"
  - "make deps"

jobs:
  include:
    - stage: elm
      install:
        - "cd ui"
        - "npm install"
      script:
        - "elm-format --validate ."
        - "npm run build"
      language: elm
      elm: "0.19.0"
    - stage: deploy
      install: "true"
      script: "curl -sL https://git.io/goreleaser | bash"
      addons:
        apt:
          packages:
            - rpm

stages:
  - test
  - elm
  - name: deploy
    if: tag IS present
